# Mycobacteroides NCBItaxid:670516
target_species_taxid: 670516
# copy into resources directory - provide your own, due to license
gatk3_jar: "GenomeAnalysisTK.jar"
gatk3_jar_url: "https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef.tar.bz2"
# base location of internal sample read data
data_dir: "test_data/"
# Replace this with the sample sheet for your own samples, see provided example
# for the format
sample_sheet: "samples.test.yaml"
# copied from a local installation of Trimmomatic - don't know where the
# adapter files live in conda-land
adapters_fasta: "workflow/resources/TruSeq3-PE.fa"
# minimum length of read to keep - see Martin et al 2018, referenced in Lee et al 2020
QC_min_length: 36
# a directory, downloaded from kraken2 ftp - see Required Files in readme.md
kraken_db: "/media/nick/hex/k2_plusfp_20220908_16"
# This is on a fast SSD, shovill faster
shovill_tempdir: "/home/nick/Downloads/tmp"
# set the amount of mem per assembly for shovill in GB
shovill_mem: 16
# dragonflye long read assembly
# these options are all or nothing, need to have dflye_medka > 0 for 
# medaka to be used at all!
# number of medaka passes 
dflye_medaka: 1
dflye_medaka_model: "r941_min_fast_g507"
dflye_medaka_opts: '-b 50'
# number of racon passes
dflye_racon: 3
# estimated genome size
dflye_genome_size: 5000000
# A tempdir can get quite large, running out of space is a failure point
mashtree_tempdir: "mashtree_tmp"
# This sequence is the definitional Erm(41) in Nash et al 2009 (PMID:19171799)
erm41_query: "workflow/resources/Erm41.fa"
# <https://www.ncbi.nlm.nih.gov/nuccore/NC_000962.3>
outgroup_assembly: "GCF_000195955.2"
# directroy for all results
results_dir: "results_test"
# default mash taxa bolletii, mmas, abscessus
mash_ref_taxa: {
    'mbolletii': 'GCF_003609715.1',
    'mmassiliense': 'GCF_000497265.2',
    #'mabscessus': 'GCF_001942505.1',
    'mabscessus': 'GCF_000069185.1'

}
# samples to exclude in stage 2
exclude_samples: []
# internal long_read_reference
# WARN - only with a single contig sequence!!! undefined behaviour for
# multi-fasta reference
internal_ref: ''
min_snp_freq: 0.90